{% set name = "gplately" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gplately-{{ version }}.tar.gz
  sha256: 5cce512295464b8353aedf581fba7b4075e0c13081a671ba18d64446a8083023

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.16.0
    - scipy >=1.0.0
    - pygplates
    - shapely
    - matplotlib-base
    - cartopy
    - platetectonictools
    - pooch
    - tqdm
    - netcdf4
    - rasterio
    - geopandas
    - stripy

test:
  imports:
    - gplately
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GPlates/gplately
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Object-orientated Python interface to pyGPlates for plate tectonic reconstructions

extra:
  recipe-maintainers:
    - brmather
    - jcannon-gplates
