{% set name = "gplately" %}
{% set version = "2.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gplately-{{ version }}.tar.gz
  sha256: afad0c576c0aa7f78c00e7c2be18a5e772d90fc26348c8f50b8bf8b10d655769

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0 

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0.0
    - wheel
    - setuptools-git-versioning
  run:
    - python >={{ python_min }}
    - numpy >=1.16.0
    - scipy >=1.0.0
    - pygplates >=1.0.0
    - shapely
    - matplotlib-base
    - cartopy
    - pooch
    - tqdm
    - netcdf4
    - rasterio
    - geopandas
    - stripy
    - plate-model-manager >=1.3.0
    - pyyaml
    - rioxarray
    - pygmt

test:
  imports:
    - gplately
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}
    - pyyaml

about:
  home: https://github.com/GPlates/gplately
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Object-orientated Python interface to pyGPlates for plate tectonic reconstructions

extra:
  recipe-maintainers:
    - brmather
    - jcannon-gplates
    - michaelchin
